In [2]:
import torch
torch.__version__

'1.8.1+cu102'

基本使用方法

In [3]:
# 创建一个矩阵
a=torch.empty(5,3)
a

tensor([[1.6932e+22, 1.8449e+28, 1.1095e+27],
        [6.7109e+22, 1.6486e+22, 4.3605e+27],
        [2.8929e+12, 7.5338e+28, 1.8037e+28],
        [3.4740e-12, 1.7743e+28, 2.0535e-19],
        [1.4609e-19, 7.5630e+28, 1.6745e+19]])

In [4]:
a=torch.rand(4,4)
a

tensor([[0.7481, 0.0364, 0.8010, 0.7603],
        [0.2166, 0.6911, 0.3191, 0.2193],
        [0.6257, 0.5788, 0.3802, 0.4321],
        [0.9042, 0.2773, 0.0907, 0.1096]])

In [5]:
# 初始化一个全0的矩阵（张量）
a=torch.zeros(5,3,dtype=torch.long)
a

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])