In [2]:
import torch
torch.__version__

'1.8.1+cu102'

基本使用方法

In [3]:
# 创建一个矩阵
a=torch.empty(5,3)
a

tensor([[1.6932e+22, 1.8449e+28, 1.1095e+27],
        [6.7109e+22, 1.6486e+22, 4.3605e+27],
        [2.8929e+12, 7.5338e+28, 1.8037e+28],
        [3.4740e-12, 1.7743e+28, 2.0535e-19],
        [1.4609e-19, 7.5630e+28, 1.6745e+19]])

In [4]:
# 生成均匀分布随机数【0-1之间】
a=torch.rand(4,4)
a

tensor([[0.7481, 0.0364, 0.8010, 0.7603],
        [0.2166, 0.6911, 0.3191, 0.2193],
        [0.6257, 0.5788, 0.3802, 0.4321],
        [0.9042, 0.2773, 0.0907, 0.1096]])

In [5]:
# 初始化一个全0的矩阵（张量）
a=torch.zeros(5,3,dtype=torch.long)
a

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
# 直接插入一个值
a=torch.tensor([5.5,3])
a

tensor([5.5000, 3.0000])

In [10]:
# 返回一个值全为1的tensor
a=a.new_ones(5,3,dtype=torch.double)
# 返回一个维度与a一样的值随机的tensor
b=torch.rand_like(a,dtype=torch.float)
a,b

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]], dtype=torch.float64),
 tensor([[0.1464, 0.3791, 0.4199],
         [0.8641, 0.2255, 0.9264],
         [0.5310, 0.6971, 0.4094],
         [0.1684, 0.6262, 0.5006],
         [0.4506, 0.5980, 0.4668]]))

In [11]:
# 展示tensor大小
a.size()

torch.Size([5, 3])

In [12]:
c=torch.rand(5,3)
# tensor 运算
b+c

tensor([[0.7610, 1.3111, 1.2629],
        [0.9623, 1.2248, 0.9304],
        [0.8595, 1.4957, 0.9073],
        [0.5861, 0.6316, 0.9369],
        [1.1565, 0.9602, 1.3596]])

In [13]:
# 也是加法
torch.add(b,c)

tensor([[0.7610, 1.3111, 1.2629],
        [0.9623, 1.2248, 0.9304],
        [0.8595, 1.4957, 0.9073],
        [0.5861, 0.6316, 0.9369],
        [1.1565, 0.9602, 1.3596]])

In [14]:
# 索引，与数组一样
b[:,1]

tensor([0.3791, 0.2255, 0.6971, 0.6262, 0.5980])

In [16]:
# 生成标准正态分布随机数【均值=0，标准差=1】
x=torch.randn(4,4)
# 改变维度
y=x.view(16)
# -1代表自动计算转成多少行（列）
z=x.view(-1,8)
print(x.size(),y.size(),z.size())
x,y,z

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


(tensor([[-0.4640,  0.5871, -0.6569,  1.0433],
         [ 0.1010,  2.5754, -1.9033,  0.0491],
         [ 0.0621, -1.1943,  0.8206, -0.4884],
         [-0.1543, -0.4383, -0.1169, -1.4913]]),
 tensor([-0.4640,  0.5871, -0.6569,  1.0433,  0.1010,  2.5754, -1.9033,  0.0491,
          0.0621, -1.1943,  0.8206, -0.4884, -0.1543, -0.4383, -0.1169, -1.4913]),
 tensor([[-0.4640,  0.5871, -0.6569,  1.0433,  0.1010,  2.5754, -1.9033,  0.0491],
         [ 0.0621, -1.1943,  0.8206, -0.4884, -0.1543, -0.4383, -0.1169, -1.4913]]))

In [17]:
# 与numpy的协同操作
a=torch.ones(5)
b=a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [18]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)