# 常见Tensor格式
- 0 scalar 标量
- 1 vector 向量
- 2 matrix 矩阵
- 3 n-dimensional tensor n维张量

In [2]:
import torch
from torch import tensor

In [3]:
# 标量 通常是一个数值
x=tensor(22.)
x

tensor(22.)

In [4]:
# 查看维度
x.dim()

0

In [6]:
2*x

tensor(44.)

In [7]:
# 从包含单个元素的张量中取出该元素值
x.item()

22.0

In [8]:
# 向量 通常指一个特征
v=tensor([0.5,1.3,-2.1])
v

tensor([ 0.5000,  1.3000, -2.1000])

In [9]:
v.dim()

1

In [10]:
v.size()

torch.Size([3])

In [11]:
# 矩阵 多维的
m=tensor([[1.,2.],[3.,4.]])
m

tensor([[1., 2.],
        [3., 4.]])

In [12]:
# 矩阵乘法
m.matmul(m)

tensor([[ 7., 10.],
        [15., 22.]])

In [13]:
tensor([1.,2.]).matmul(m)

tensor([ 7., 10.])